dist: trusty
sudo: require
language: cpp
osx_image: xcode9.4

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.9
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.9
      - gcc-6
      - g++-6
      - cmake

matrix:
  exclude: # On OSX g++ is a symlink to clang++ by default
    - os: osx
      compiler: gcc
  include:
    - compiler: gcc
      env: COMPILER=g++-6

    - compiler: clang
      env: COMPILER=clang++-3.9


before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo apt-get -qq update;    fi

before_script:
  - if [ "$COMPILER" = "g++-6"        ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="g++-6" CC="gcc-6";              fi
  - if [ "$COMPILER" = "clang++-3.9"  ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.9" CC="clang-3.9";    fi

script:
  #Build & Install library
  - (mkdir -p lib/build-debug/ &&  cd lib/build-debug && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=~/.local/ .. && cmake --build . --target install)
  - (mkdir -p lib/build-release/ &&  cd lib/build-release && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/.local/ .. && cmake --build . --target install)
  # Run tests
  - (mkdir -p test/build-debug/ &&  cd test/build-debug && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=~/.local/ .. && cmake --build . && ctest -V .)
  - (mkdir -p test/build-release/ &&  cd test/build-release && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/.local/ .. && cmake --build . && ctest -V .)

